version: '3'

services: 
  consul1:
    image: consul:latest
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "agent -server -bootstrap-expect 3 -ui -disable-host-node-id -client 0.0.0.0"
    networks:
      - sky-net
  
  consul2:
    image: consul:latest
    command: "agent -server -join consul1 -disable-host-node-id"
    networks:
      - sky-net
    links: 
      - consul1
  
  consul3:
    image: consul:latest
    hostname: "consul3"
    command: "agent -server -join consul1 -disable-host-node-id"
    networks:
      - sky-net
    links:
      - consul1

  product-service:
    image: meongbego/product
    environment: 
      - PRODUCT_SERVICE_HOST=0.0.0.0
      - PRODUCT_SERVICE_PORT=8100
      - CONSUL_HTTP_ADDR=consul1:8500 
    command: go run main.go
    ports: 
      - "8100:8100"
    links:
      - consul1
    networks:
      - sky-net

  user-service:
    image: meongbego/user
    environment: 
      - USER_SERVICE_HOST=0.0.0.0
      - USER_SERVICE_PORT=8080
      - CONSUL_HTTP_ADDR=consul1:8500
    ports: 
      - "8080:8080" 
    command: go run main.go
    links:
      - consul1
    networks:
      - sky-net

networks:
  sky-net:
    driver: bridge